from tkinter import *
s=Tk()
s.geometry('800x800')
s.resizable(False,False)
s.title('Students Mark Sheet')
s.configure(bg='white')

l=Label(s,text='STUDENT MARK SHEET',bg='white',font=("arial bold",24))
l.place(x=5,y=0)

l1=Label(s,text='NAME', bg="white",fg='black')
l1.place(x=5,y=60)
l2=Entry(s,width=20,border=2)
l2.place(x=55,y=60)


l3=Label(s,text='Roll No:', bg="white",fg='black')
l3.place(x=200,y=60)
l4=Entry(s,width=20,border=2)
l4.place(x=250,y=60)

l5=Label(s,text='SUBJECTS', bg="black",fg='white',font='bold',width=20, borderwidth=1,relief='solid',highlightthickness=1,highlightcolor='white')
l5.place(x=5,y=150)
l6=Label(s,text='MARKS', bg="black",fg='white',font='bold',width=20, borderwidth=1,relief='solid',highlightthickness=1,highlightcolor='white')
l6.place(x=185,y=150)
l7=Label(s,text='GRADE', bg="black",fg='white',font='bold',width=20, borderwidth=1,relief='solid',highlightthickness=1,highlightcolor='white')
l7.place(x=365,y=150)

l8=Label(s,text='ENGLISH', bg="grey",fg='black',font='bold',width=20, borderwidth=1,relief='solid')
l8.place(x=5,y=174)
l9=Entry(bg="grey",fg='black',font='bold',width=20, borderwidth=1,relief='solid')
l9.place(x=185,y=174)
l10=Entry(bg="grey",fg='black',font='bold',width=20, borderwidth=1,relief='solid')
l10.place(x=365,y=174)

l11=Label(s,text='HINDI', bg="grey",fg='black',font='bold',width=20, borderwidth=1,relief='solid')
l11.place(x=5,y=198)
l12=Entry(bg="grey",fg='black',font='bold',width=20, borderwidth=1,relief='solid')
l12.place(x=185,y=198)
l13=Entry(bg="grey",fg='black',font='bold',width=20, borderwidth=1,relief='solid')
l13.place(x=365,y=198)

l14=Label(s,text='SCIENCE', bg="grey",fg='black',font='bold',width=20, borderwidth=1,relief='solid')
l14.place(x=5,y=222)
l15=Entry(bg="grey",fg='black',font='bold',width=20, borderwidth=1,relief='solid')
l15.place(x=185,y=222)
l16=Entry(bg="grey",fg='black',font='bold',width=20, borderwidth=1,relief='solid')
l16.place(x=365,y=222)

l17=Label(s,text='MATHS', bg="grey",fg='black',font='bold',width=20, borderwidth=1,relief='solid')
l17.place(x=5,y=246)
l18=Entry(bg="grey",fg='black',font='bold',width=20, borderwidth=1,relief='solid')
l18.place(x=185,y=246)
l19=Entry(bg="grey",fg='black',font='bold',width=20, borderwidth=1,relief='solid')
l19.place(x=365,y=246)

def submit():
    l20=Label(s,text='Student Name',bg='white')
    l20.place(x=5,y=350)
    l21=Label(s,text=l2.get(),bg='white',fg='red')
    l21.place(x=90,y=350)
    l22=Label(s,text='Roll No:',bg='white')
    l22.place(x=5,y=374)
    l23=Label(s,text=l4.get(),bg='white',fg='red')
    l23.place(x=90,y=374)

    l24=Label(s,text='GRADE CARD',bg='white',font=('arial bold',12))
    l24.place(x=5,y=420)
    l25=Label(s,text='Out of 400',bg='white',font=('arial bold',12))
    l25.place(x=5,y=450)

    l26=Label(s,text='SUBJECTS', bg="blue",fg='white',font='bold',width=20, borderwidth=1,relief='solid',highlightthickness=1,highlightcolor='white')
    l26.place(x=5,y=476)
    l27=Label(s,text='MARKS', bg="blue",fg='white',font='bold',width=20, borderwidth=1,relief='solid',highlightthickness=1,highlightcolor='white')
    l27.place(x=185,y=476)
    l28=Label(s,text='GRADE', bg="blue",fg='white',font='bold',width=20, borderwidth=1,relief='solid',highlightthickness=1,highlightcolor='white')
    l28.place(x=365,y=476)

    l29=Label(s,text='ENGLISH', bg="sky blue",fg='black',font='bold',width=20, borderwidth=1,relief='solid')
    l29.place(x=5,y=500)
    l30=Label(s,text=l9.get(),bg="light blue",fg='red',font='bold',width=20, borderwidth=1,relief='solid')
    l30.place(x=185,y=500)
    l31=Label(s,text=l10.get(),bg="light blue",fg='red',font='bold',width=20, borderwidth=1,relief='solid')
    l31.place(x=365,y=500)

    l32=Label(s,text='HINDI', bg="sky blue",fg='black',font='bold',width=20, borderwidth=1,relief='solid')
    l32.place(x=5,y=524)
    l33=Label(s,text=l12.get(),bg="light blue",fg='red',font='bold',width=20, borderwidth=1,relief='solid')
    l33.place(x=185,y=524)
    l34=Label(s,text=l13.get(),bg="light blue",fg='red',font='bold',width=20, borderwidth=1,relief='solid')
    l34.place(x=365,y=524)

    l35=Label(s,text='SCIENCE', bg="sky blue",fg='black',font='bold',width=20, borderwidth=1,relief='solid')
    l35.place(x=5,y=548)
    l36=Label(s,text=l15.get(),bg="light blue",fg='red',font='bold',width=20, borderwidth=1,relief='solid')
    l36.place(x=185,y=548)
    l37=Label(s,text=l16.get(),bg="light blue",fg='red',font='bold',width=20, borderwidth=1,relief='solid')
    l37.place(x=365,y=548)

    l38=Label(s,text='MATHS', bg="sky blue",fg='black',font='bold',width=20, borderwidth=1,relief='solid')
    l38.place(x=5,y=572)
    l39=Label(s,text=l18.get(),bg="light blue",fg='red',font='bold',width=20, borderwidth=1,relief='solid')
    l39.place(x=185,y=572)
    l40=Label(s,text=l19.get(),bg="light blue",fg='red',font='bold',width=20, borderwidth=1,relief='solid')
    l40.place(x=365,y=572)

    l41=Label(s,text='YOUR TOTAL SCORE:',bg='white',font=('arial',8))
    l41.place(x=5,y=610)
    l42=Label(s,text='PERCENTAGE OBTAINTED:',bg='white',font=('arial',8))
    l42.place(x=5,y=630)
    l43=Label(s,text=int(l9.get())+int(l12.get())+int(l15.get())+int(l18.get()),bg='white',fg='red')
    l43.place(x=120,y=610)
    l44=Label(s,text=int(l9.get())+int(l12.get())+int(l15.get())+int(l18.get()*(0.4)),bg='white',fg='red')
    l44.place(x=140,y=630)

sub=Button(s,text='SUBMIT',bg='light blue',fg='white',command=submit)
sub.place(x=450,y=280)



s.mainloop()